version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: expense-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
