spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_db
    username: your_db_user
    password: your_db_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080
